spring.application.name=all-agency-backend
# ========================================
# CONFIGURATION DU SERVEUR
# ========================================
server.port=8080

# URL pour WebClient
agency.dashboard.url=http://localhost:8081/api/events
agency.dashboard.connect-timeout-ms=5000

# ========================================
# CONFIGURATION R2DBC POSTGRESQL (Réactif)
# ========================================
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/agency_booking_db
spring.r2dbc.username=postgres
spring.r2dbc.password=root


# application.properties
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# Pool de connexions
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20

# ========================================
# CRÉATION AUTOMATIQUE DES TABLES
# ========================================
# Attention : en production, utilisez Flyway ou Liquibase
spring.r2dbc.initialization-mode=always

# ========================================
# LOGS
# ========================================
logging.level.root=INFO
logging.level.com.agencybooking=DEBUG
logging.level.org.springframework.r2dbc=DEBUG

# ========================================
# URL DU BACKEND EXTERNE (AgencyConnect Dashboard)
# ========================================
external.backend.url=http://localhost:8081/api/events
external.backend.timeout=5000

# ========================================
# CONFIGURATION WEBCLIENT
# ========================================
spring.codec.max-in-memory-size=10MB
spring.sql.init.mode=always